"""Wavefront OBJ export.

OBJ rather than a CARLA-native format on purpose: CARLA ingests custom props through an
Unreal content package, which needs a source build, and pinning the geometry to that pipeline
would make it unusable by any other renderer or by an offline check. OBJ is imported by the
CARLA asset workflow, by Blender, and by every mesh library, so the geometry stays portable.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Iterable

    from smc.carla_gen.geometry import Mesh


def write_obj(meshes: Iterable[Mesh], path: Path | str, *, material: str | None = None) -> Path:
    """Write meshes to a single OBJ, one named group per mesh.

    OBJ vertex indices are 1-based and global to the file, so each mesh's faces are offset by
    the running vertex count.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = ["# generated by smc.carla_gen — do not edit"]
    if material is not None:
        lines.append(f"mtllib {material}")

    offset = 1
    for mesh in meshes:
        if len(mesh.vertices) == 0:
            continue
        lines.append(f"o {mesh.name}")
        if material is not None:
            lines.append("usemtl surface")
        lines.extend(f"v {x:.6f} {y:.6f} {z:.6f}" for x, y, z in mesh.vertices)
        lines.extend(
            f"f {a + offset} {b + offset} {c + offset}" for a, b, c in mesh.faces.tolist()
        )
        offset += len(mesh.vertices)

    path.write_text("\n".join(lines) + "\n")
    return path
